### ISSUE TITLE
Importing inside function is impacting performance.

### ISSUE THREAD

**Issue by mlevy94** [ludios/Desktopmagic#6]
I noticed that in [def _getRectAsImage](https://github.com/ludios/Desktopmagic/blob/906cbe16f4e6c5fea7121c186ff8c6e7c997b2f7/desktopmagic/screengrab_win32.py#L320
) Image is being imported inside the function. Is there any reason for this to not take place outside this function? 

https://wiki.python.org/moin/PythonSpeed/PerformanceTips#Import_Statement_Overhead

**Comment by ivan** [comment]
I would guess it would be hard to measure the difference with `timeit` because of the overhead in the rest of the function, but you are welcome to prove me wrong!

**Comment by mlevy94** [comment]
I provided an example link that outlines the impact. I can do actual
testing tonight.

**Comment by ivan** [comment]
I'll reopen this if you that find the difference is measurable with `_getRectAsImage`.
